
INSERT INTO materia (nombre)
VALUES ('DESARROLLO DE APLICACIONES CON WEB FRAMEWORKS');
INSERT INTO materia (nombre)
VALUES ('SERVIDORES EN PLATAFORMAS PROPIETARIAS');
INSERT INTO materia (nombre)
VALUES ('SERVIDORES EN PLATAFORMAS LIBRES');
INSERT INTO materia (nombre)
VALUES ('DESARROLLO DE APLICACIONES MULTIPLATAFORMAS');
INSERT INTO materia (nombre)
VALUES ('ALGEBRA VECTORIAL');


INSERT INTO alumno(nombre,apellido,id_materia)
VALUES ('MARIELA JULISSA','VENTURA IRAHETA',1);
INSERT INTO alumno(nombre,apellido,id_materia)
VALUES ('MARIA ALEXANDRA','ROSALES MENA',2);
INSERT INTO alumno(nombre,apellido,id_materia)
VALUES ('JUAN JOSE','PEREZ VAZQUEZ',3);
INSERT INTO alumno(nombre,apellido,id_materia)
VALUES ('JUAN JOSE','PEREZ VAZQUEZ',4);
INSERT INTO alumno(nombre,apellido,id_materia)
VALUES ('OSCAR ADOLFO','NAVAS LOPEZ',5);